codyborders/abandoned_camel_coffee_mercantile

app/views/beans/index.html.erb
db/seeds.rb

Adding a seed file for beans to initially populate the database with random collection of beans.

add seed file for beans

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/cart_controller.rb
app/models/cart.rb
app/views/beans/index.html.erb
app/views/cart/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/schema.rb
spec/features/guest_can_add_item_to_cart_spec.rb
spec/features/guest_visits_items_index_spec.rb
spec/features/user_can_view_cart_spec.rb
spec/models/cart_spec.rb
spec/rails_helper.rb
spec/support/factories.rb
spec/support/factory_girl.rb

Adds feature testing for cart, creates cart controller and cart model. Gives ability to user to add items to cart and visit page that displays items that are added to cart.

Adding items to cart #5

---

app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/models/category.rb
config/routes.rb
db/migrate/20170223005254_add_slug_to_category.rb
db/migrate/20170223010734_add_index_to_categories.rb
db/schema.rb
spec/features/categories/user_visits_category_show_page_spec.rb
spec/features/guest_visits_items_index_spec.rb

Adds home controller and moves logic from Application Controller.

Updates guest visits index spec

---

app/controllers/cart_controller.rb
app/views/layouts/application.html.erb
db/schema.rb
spec/features/guest_visits_items_index_spec.rb
spec/features/user_can_view_cart_spec.rb

finishes adding to cart, testing for it, and adds a cart link to the navbar
@JonathanSR 
@codyborders 
@andrewdwooten

finish add to cart

---

.hound.yml
.rubocop.yml

Add .hound.yml and .rubocop.yml files to root directory of project.
Per the configuration directions for hound, I modified the base
settings for rubocop which have been throwing the quotation mark
errors.

Hound Configure

---

app/controllers/categories_controller.rb
app/views/categories/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/schema.rb
db/seeds.rb
spec/features/categories/user_visits_categories_index_spec.rb

> Add feature test for guest visiting categories index.  Test confirms
> presence of h2 title and h3 headings for categories thumbnails.
> Test confirms guest can navigate to a category show page from
> category index by clicking the 'Shop Now' button within a
> category thumbnail.  Also adds to seed file such that it will generate
> categories.  Tests currently passing."

Categories index fix

---

app/controllers/users_controller.rb
app/models/cart.rb
app/views/cart/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb

Adds login/logout and checkout buttons that exist based on the status of a user (visitor/user)

adds user status specific buttons

---

app/controllers/beans_controller.rb
app/models/bean.rb
app/views/beans/show.html.erb
db/migrate/20170224175919_add_column_to_beans.rb
db/schema.rb
spec/features/user_visits_retired_item_page_spec.rb

Adds Feature Testing for Bean status, active or retired. Adds Bean status feature.

Retired items #29

---

app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/controllers/users_controller.rb
app/models/bean.rb
app/views/layouts/application.html.erb
spec/features/users/user_cannot_see_unathorized_data_spec.rb

Adds feature testing for authenticated user, unauthorized access, to other user's data. Missing unauthorized access to admin functionality due to admin not being implemented. Will add the mentioned check to branch issue #32.

adds unathorized access method for user

---

app/views/layouts/application.html.erb
spec/features/users/user_transfers_cart_from_visitor_spec.rb
spec/features/visitor_and_user_see_specific_links_spec.rb

adds testing for visitor with items in cart logging in as a user.

adds testing for user

---

app/views/orders/show.html.erb
spec/features/visitor/unauthorized_user_cannot_access_unauthorized_data_spec.rb
spec/features/visitor/visitor_checks_out_spec.rb

Changes display of most recent order to be displayed in a
table as per user story. Feature test modified to query
new css ids.  Test currently passing.  Also modifies
failing visitor test as the css selector did not conform
to the reformatted button.  All tests currently passing.

Format New Order display

---

app/controllers/orders_controller.rb
app/models/order.rb
app/views/orders/index.html.erb
config/routes.rb
spec/features/users/user_views_all_past_orders_spec.rb

> Add index route to orders in routes.rb.  Add index method to orders_controller.
> Index method queries the orders of the current_user to prevent cross-user
> order-viewing.  Add index.html.erb to orders views.  Same uses a striped-table
> to display the order id, order item-count, order date, the total price of
> the order, and a button which links to the show page of the individual order.
> All tests are currently passing and local testing shows the view to be
> rendering with anticipated formatting."

View past orders #27

---

app/controllers/orders_controller.rb
app/models/bean.rb
app/models/order.rb
app/views/orders/index.html.erb
app/views/orders/show.html.erb
config/routes.rb
spec/features/users/user_views_a_past_order_spec.rb
spec/features/users/user_views_all_past_orders_spec.rb
spec/features/visitor/visitor_checks_out_spec.rb

> Add feature test to prove user can view a single order in their history.
> Restyled orders show page to conform to user story provided. Add method
> to bean to determine its subtotal with a given quantity.  View includes
> simple ruby logic to determine if a condition applies to render the
> orders update to status time. Same utilizes a new method in the order
> model to determine if it's status is completed or cancelled. All
> feature tests are presently passing. It was necessary to modify
> user checks out feature test to conform to new styling of
> order show page."

Viewing a past order #28

---

app/controllers/cart_controller.rb
app/controllers/orders_controller.rb
app/controllers/sessions_controller.rb
app/models/bean.rb
app/models/user.rb
app/views/layouts/application.html.erb
spec/models/user_spec.rb

Modifies flash messages to center them, color-coordinate them and drops them below the navbar. Adds model testing for user.

Model spec user #64

---

app/views/layouts/application.html.erb

Removes both functionless dropdowns as well as
functionless search bar from navbar.

Remove bad navbar elements

---

app/views/layouts/application.html.erb

Add user dashboard link to navbar for logged in users

---

app/views/users/show.html.erb
spec/features/users/user_logs_in_spec.rb

> Added Bootstrap styling to user dashboard. Added elements of user
> to display per the user story. Modified user_logs_in_spec to test
> same. Test is currently passing. Local examination of view shows
> it to be functioning appropriately.

User dashboard #86

---

app/controllers/admin/orders_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/admin/orders/show.html.erb
app/views/application/admin_dashboard.html.erb
app/views/users/new.html.erb
config/routes.rb
db/migrate/20170227211021_add_name_and_address_attributes_to_user.rb
db/schema.rb
spec/factories/users.rb
spec/features/admin/admin_logs_in_spec.rb
spec/features/admin/admin_user_dashboard_spec.rb
spec/features/admin/admin_views_a_single_order_spec.rb
spec/features/admin/admin_visits_dashboard_spec.rb
spec/features/users/user_creates_new_account_spec.rb
spec/features/users/user_logs_in_spec.rb
spec/features/users/user_transfers_cart_from_visitor_spec.rb
spec/features/users/user_views_a_past_order_spec.rb
spec/features/users/user_views_all_past_orders_spec.rb
spec/features/visitor/visitor_checks_out_spec.rb
spec/models/order_spec.rb

Adds functionality for admin to view a single order per user story. Modifies user model; adds first_name, last_name, street, city, state, and zip to user table.  Adds presence validation to all new attributes.  Modifies views and feature testing where necessary to allow appropriate function to occur. All tests currently passing except for guest_can_remove_an_item_from_cart_spec.rb and 
admin_visits_dashboard_spec.rb. Both were failing prior to changes and are a WIP.

Admin views an individual order #65

---

spec/models/user_spec.rb

Added tests for all validations to user
including first name, last name, street, city,
state, and zip. Test passing.

Add validations to user model testing

---

app/views/admin/orders/show.html.erb
app/views/beans/show.html.erb
spec/features/admin/admin_views_a_single_order_spec.rb
spec/features/beans/guest_visits_bean_show_page_spec.rb
spec/features/beans/guest_visits_items_index_spec.rb
spec/features/users/user_views_all_past_orders_spec.rb
spec/models/bean_spec.rb
spec/models/order_spec.rb

Amended admin_show page/test, bean show page/test,
user_views_past_orders_spec,
user_visists_item_index_spec,
and model testing for bean and model.

Fix tests #99

---

app/models/bean.rb
db/seeds.rb
spec/features/admin/admin_visits_dashboard_spec.rb
spec/models/bean_spec.rb

Modify seed file to generate 10 beans per category.
Modify necessary line in bean.rb per serrano; fixes
failing tests. Modified generation of orders, beans, and
admin in admin dashboard test; manual verification shows
page rendering appropriately; assertion unable to find
css element. All tests passing except admin_visits_
dashboard_spec.rb

Modify Seed File

---

app/assets/stylesheets/application.scss
app/views/categories/show.html.erb

Removed syntax error from application.scss that
was causing test failure and abnormal site
behavior. Added bootstrap formatting to category
show page, not the category index.  Small typo in the
title of this commit. All tests passing except admin
dashboard spec.

Bootstrap Category index
